project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    code-fold: true 
    comments:
      hypothesis: true
  docx: default
  pdf: default
  
execute:
  freeze: false
  output: asis 

editor: visual

